// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh8j7yaAaV1DNE-jesB32xIr6dHz4SmXQ',
    appId: '1:105063535444:web:789e965282da4bf499eec1',
    messagingSenderId: '105063535444',
    projectId: 'dating-app-12ac7',
    authDomain: 'dating-app-12ac7.firebaseapp.com',
    databaseURL: 'https://dating-app-12ac7-default-rtdb.firebaseio.com',
    storageBucket: 'dating-app-12ac7.firebasestorage.app',
    measurementId: 'G-56N068FXPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ9Kck350PEHcugm_uhQt2Zi53r3Mnn-s',
    appId: '1:105063535444:android:d5fd8c6152f75ca199eec1',
    messagingSenderId: '105063535444',
    projectId: 'dating-app-12ac7',
    databaseURL: 'https://dating-app-12ac7-default-rtdb.firebaseio.com',
    storageBucket: 'dating-app-12ac7.firebasestorage.app',
  );
}
